### ISSUE TITLE
incorrect marking of menu bar

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#103]
AS A logged in User
I WANT TO only see one menu item selected
TO get not confused which menu is selected

Case: Whenever I click in the menu bar on "Marcel" (so my profile) the page appears correct but on the menu bar "Player" and "Marcel" are both highlighted. Only one topic should be highlighted at a time. It should be the page displayed at the moment.

![image](https://user-images.githubusercontent.com/29160369/33049051-8c93b726-ce5e-11e7-80e7-28937b94735c.png)

ACCEPTANCE CRITERIA
 - When I click on my name on the upper menu I want to get onto my account page and see only this menu item selected

**Comment by GittiHab** [comment]
Should resolve itself automatically with #223
