### ISSUE TITLE
create a tournament

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#104]
**As a** tournament organizer
**I want to** be guided through the tournament creation  
**In order to** simplify my work
**Acceptance Criteria:**
 - builds on Event model (#49)
 - Adapt the existing new event Page + logic (#19)
 - [ ] only KO-system (single elimination) is required for now and it should be the only choosable option for now
 - Creation should work the following way:
       1) You come from the Event choosing page (lower page in #110)
     2.1) You come to a Page where you have to enter Eventname, Beschreibung,  Team/Einzelteilnahme (Team min,max size), Startdatum, Länge eines Spieltags in Tagen (this field will be added in #145)
     2.2) additional fields should not be required(please check this), but should be fillable: Anmeldeschluss, Sportart, max Teamzahl, Enddatum
     3) After event creation, you should be redirected to the Page of the new Event
 - please synchronize with "team bruteforce" on the functionality of this page and check, whether its concept is implementable in this Version
 - [ ] additional validations(if entered): Anmeldeschluss <= Startdatum <= Enddatum

**Comment by MerlindlH** [comment]
the mentioned page1 can be seen in #95 and a explanation of the bigger event creation process can be seen for example in #110
