### ISSUE TITLE
Types of events

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#110]
AS a user
I WANT to be able to create events of different types
IN ORDER to choose type that match to my event.

**Comment by stursberg** [comment]
- "Events" page has a button "New event" on the top:

![Screen Shot 2017-11-22 at 17.40.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f16b7191a379e80c2f51415d47be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec959f54de9455da6173467f43b.png)
 
 
- After you push the button "New event" you come to the page "Create new event" with 3 following options:

![Screen Shot 2017-11-22 at 17.45.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f16b7191a379e80c2f54415b4ebe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f54de84c50a016356bf43b.png)
 
 
- Click on "League" => is the same like now click on button "New" from the page "Events".
- 2 other options are now inactive.

**Comment by GittiHab** [comment]
Does this relate to #19, #104 and #95?

**Comment by MarcelSchmidberger** [comment]
This page mentioned in #110 will link to the creation pages of the different event types shown in #104 and #95 . So when clicking on create new event #110 will be displayed and from here you can navigate to the different event types creation processes (create-league, create- Tournament, create Rangliste )

**Comment by jkbe** [comment]
@MarcelSchmidberger the same applies to #19?
