### ISSUE TITLE
English Cucumber tests crash with missing translations

### ISSUE THREAD

**Issue by jkbe** [hpi-swt2/sport-portal#112]
In #111 the main language for the application was set to German but the language for the Cucumber feature tests remained English. Now, when somebody adds only the German translation (which should be legal) for an i18ned string, the Cucumber tests can fail.

Issue was initially discovered through this failed build: https://travis-ci.org/hpi-swt2/sport-portal/builds/306447038

**Comment by jak-ing** [comment]
Issue was initially discovered through this failed build: https://travis-ci.org/hpi-swt2/sport-portal/builds/306447038
