### ISSUE TITLE
Users controller causes nil error on resource authorization

### ISSUE THREAD

**Issue by fpottbaecker** [hpi-swt2/sport-portal#163]
See [this error.](https://swt2-errbit-2017.herokuapp.com/apps/5a031be36caee90014ce8531/problems/5a1d947d46d3bb00089d941f)

When a user that is not signed in tries to access the edit page of an existing user, this error occurs.

No way to fix this is known so far.

**Comment by bakoe** [comment]
We had a similar problem while implementing #28. The solution was to explicitly define the resource that should be initialized via 

```ruby
load_and_authorize_resource :team
```

(see teams_controller.rb)

Maybe this could help here too?

**Comment by fpottbaecker** [comment]
@bakoe sadly that did not help, however, i found another fix for this.
