### ISSUE TITLE
Spielplan for Tournaments

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#169]
**As a** tournament participant
**I want to** have a page with all currently played matches (Spiele)
**In order to** to have an overview of what happens in the tournament
**Acceptance Criteria:**
 - builds on #35 
 - [x] After the start of the Tournament, a Spielplan should be calculated (with random teampairing and single elimination)
 - [X] There should be different Spieltage which show the Spiele of the current Spieltag / Tournament Stage
 - [x] Each Spieltag should contain the list of current Spiele (in a Tournament each Round will be calculated according to the results of the previous Spieltag)
 - [x] Spieltage should have placeholderstrings if game information (who won games) is not available yet. the placeholderstrings should contain the needed games (e.g."Gewinner aus Achtelfinalspiel 1 gegen Gewinner aus Achtelfinalspiel 2") 
 -  [x] The last Spieltag should contain the matches for determining the first, second and third winner ("Finale" and "Spiel um Platz 3" if wanted)

prototypical demo:

![turnirspielplan](https://user-images.githubusercontent.com/8302493/33373858-07e8fd90-d504-11e7-97a4-a02417776728.png)

**Comment by Markus-Brand** [comment]
Old Size: 20
New Size: 8

**Comment by MerlindlH** [comment]
note: no additional deadlines between the tournament steps are needed (cf. [PO meeting protocol of the 5th of Jaunary](https://github.com/hpi-swt2/sport-portal/wiki/PO-Meeting-5th-January))
