### ISSUE TITLE
Tournament overview table

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#170]
**As a** tournament participant
**I want to** have a page that shows the progress/history of the tournament
**In order to** see how far each team came / its status

**Acceptance Criteria:**
 - [x]  Table with columns: Team-Name | Platzierung |
 - [x] Platzierung should show how far the players is/got in the Tournament (e.g. "ist momentan im Viertelfinale", "ist im Viertelfinale ausgeschieden", "Erster/Zweiter/Dritter/Vierter Platz")
 - [x] the table should be in sync with the progression of the Tournament, and be found / linked on the event page (compare to #31, #32, synchronize with Team issue number 5)

prototypical Table:

|Team-name|Platzierung|
|-------|------------|
|Team1        |im Viertelfinale ausgeschieden|
|Team2       |im Finale (gegen bla, falls bekannt)|
|Team3|im Halbfinale  ausgeschieden|
|Team4|im Viertelfinale ausgeschieden|
|Team5|im Viertelfinale ausgeschieden|
|Team6|im Halbfinale|
|Team7|im Viertelfinale ausgeschieden|
|Team8|im Halbfinale|

**Comment by GittiHab** [comment]
I am afraid that you will have to fix the problem of tournaments not being viewable at the moment in order for this user story to be accepted 😕.

**Comment by ErikBrendel** [comment]
In Absprache mit PO wird `(gegen Bla, falls bekannt)` aus der Story genommen. Zu finden unter #376
