### ISSUE TITLE
Unstable columns on team page

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#179]
Columns on team page shift depending on the visibility of checkboxes (probably). Columns should be stable.

<img width="937" alt="sportify" src="https://user-images.githubusercontent.com/27727717/35573993-ec580b9c-05d8-11e8-9d46-3018a694ef6d.png">

**Comment by bakoe** [comment]
@svitlanakalancha Hi! Can you please check whether this issue is still relevant? To my mind, the changes regarding the Team page re-design (#381) made this issue obsolete since there is no table on the Show Team page anymore.

If the issue is not relevant anymore, please close it. 🙂

**Comment by svitlanakalancha** [comment]
agreed :)
