### ISSUE TITLE
index method in Matches Controller missing

### ISSUE THREAD

**Issue by manner** [hpi-swt2/sport-portal#180]
`/matches` page doesn't render, because index method was removed in PR #153.

**Comment by Askir** [comment]
This is intended behaiviour, matches page was to be removed with the implementation of a schedule page. If the link to that page does exist it has been included in another pull request and somebody messed up the merging. Ask @MarcelSchmidberger for more information on this.

**Comment by Askir** [comment]
Actually, we seem to have forgotten to delete the matches_link in the navbar so we'll do that :)
