### ISSUE TITLE
Header design

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#183]
Header will be shown on the top of every page. There is no top-margin needed.
  
![Screen Shot 2017-11-29 at 16.36.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fa6b7191a379e90c2857415d4fbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959ff4de84555a2113f63f43b.png)
 
- Maximum width of content (= header from logo to login button): 1200px; Width of background (color/pic) is not limited;
- transitions when menu opens (open from top to bottom), use materialize again?
- all data (for example font size, colors etc - in mock; ask Dima for CSS);
- Font: ProximaNova

**Estimation: XL**

Version for mobile (just styling, no new menu entries, 2nd pic --> click on Dmitri --> 3rd pic)
![Screen Shot 2017-11-29 at 16.51.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fa6b7191a379e90c2e50415f4dbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959ff4ce14b52ad113764f43b.png)

The result should look like this (Acceptance Criteria):
 
![Screen Shot 2017-11-29 at 17.05.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456fa6b7191a379e80c2b54415e4dbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959ff4ce04a51a6163f67f43b.png)

- [ ] Implement styling of desktop view
- [ ] Implement styling of mobile view

**Comment by stursberg** [comment]
[header.zip](https://github.com/hpi-swt2/sport-portal/files/1515235/header.zip)
[ProximaNova.zip](https://github.com/hpi-swt2/sport-portal/files/1515237/ProximaNova.zip)

**Comment by jkbe** [comment]
**Reestimation** after having gained experience with the topic in #185: **L (Actual: XL)**

**Comment by emanuel-metzenthin** [comment]
Fixed a few PO requests. But the header is not transparent for the moment.

**Comment by stursberg** [comment]
all the links in user-menu should be on the left (not in the center)

![Screen Shot 2018-01-19 at 11.39.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455fa6b7191a379ee0c2858415e4dbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95ef54ee94957a0103f62f43b.png)
