### ISSUE TITLE
Create Event Error - Error when creating and wrong display in Eventlist

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#187]
When trying to create a new event an error occurs every time!

![image](https://user-images.githubusercontent.com/29160369/33392859-925d4f56-d53d-11e7-9ca2-8db9b28c421b.png)

![image](https://user-images.githubusercontent.com/29160369/33392971-e5e10bcc-d53d-11e7-815e-c0e5fd8af379.png)

If you visit the eventlist after the error the event seams to be listed, but incorrectly: The columns show the wrong data. 

![image](https://user-images.githubusercontent.com/29160369/33393179-9965ae8c-d53e-11e7-93a7-76b047012132.png)

The columns should be shifted to match the headline and the data columns of max Teams seem to be missing.

![image](https://user-images.githubusercontent.com/29160369/33393325-23a3de34-d53f-11e7-9e7d-230d39a60edc.png)

**Comment by Askir** [comment]
Table has been fixed and the error is due to authentification problems, can this issue be closed?

**Comment by MarcelSchmidberger** [comment]
Yes, thanks for reminding me. I intended to do so yesterday. I remarked permission management on the todo list for the next sprint.
