### ISSUE TITLE
Fix all Rubocop warnings

### ISSUE THREAD

**Issue by jkbe** [hpi-swt2/sport-portal#192]
When I execute the linter on my machine using `$ rubocop`, I get a lot of old warnings and error messages. They don't help me with identifying the new warnings that I introduced on my branch before I push to GitHub and get a 'failed' notification from CodeClimate.

**Comment by fpottbaecker** [comment]
`rubocop -a`

**Comment by jkbe** [comment]
Yup, will create a PR in a bit.
