### ISSUE TITLE
Mandatory fields in team creation form

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#218]
**Mandatory fields** in team creation form should be **recognizable**.

**Actual behaviour**

- User clicks on button "Create team"
- User sees the form
- User doesn't know what fields are mandatory to fill 
- If name isn't filled, user lands on error page

**Correct behaviour**

- User sees on the form page what fields are mandatory
- Fields are marked with * sign

**Comment by niconomaa** [comment]
technical tasks

- [x] write view tests that verify presence of asterisk and footnote with explanation of mandatory fields
- [x] edit view so that it now labels obligatory fields
