### ISSUE TITLE
Rearranging of create Event Button

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#220]
**AS AN** user
**I WANT** only one button to create new events on the *all events* page
**SO THAT** the navigation bar is more clean

## Acceptance Criteria
- [x] When logged in the "Neues Event erstellen" button should be visible next to the title (*Events*) on the *All Events* page
- [x] There is not "Veranstaltung erstellen" button in the menubar

**Comment by GittiHab** [comment]
Looks good 😃
