### ISSUE TITLE
No synonyms of the term "Event"

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#222]
**AS AN** user
**I WANT** only a single term to be used to describe events

## Acceptance Criteria
- [x]  Everything should uniformly be called "Event", all designations *Veranstaltung* should be replaced with "Event"

Places where it occurred:
https://sport-portal-dev.herokuapp.com/createEvent

**Comment by GittiHab** [comment]
Das ist wohl ein Typo unter https://sport-portal-dev.herokuapp.com/events/new (Event**s**art)
<img width="377" alt="screen shot 2018-01-06 at 12 50 42" src="https://user-images.githubusercontent.com/6453623/34639413-39a3fe30-f2e0-11e7-8b4a-6790391853cb.png">

**Comment by GittiHab** [comment]
Still the same problem... can't see a difference.
