### ISSUE TITLE
Two-Step event creation form

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#227]
**AS A** creator of an event
**I WANT TO** have a two-step event creation form
**SO THAT** I can select the event type before entering other options and type specific options

## ACCEPTANCE CRITERIA
- [x] When clicking on the "New" Button on the "All Events" page the next screen should ask me which event type I would like to create (League, Tournament or Ranking List)
- [x] After I have selected the event type a page is opened where all the general event options as well as the type specific options are

The event type specific options are implemented in  #197,  #104 and by the team [bruteforce](https://github.com/hpi-swt2/sport-portal/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22team+bruteforce%22+)

**Comment by GittiHab** [comment]
Mockup

![two_step](https://user-images.githubusercontent.com/6453623/33795232-ebab67c6-dcdd-11e7-95ea-eec9ddd87372.jpg)

**Comment by MarcelSchmidberger** [comment]
how does this differ from what is already there? 
The "Event type" field should be removed and the "Spielsystem" field should show the correct content, depending on the event type selected in the "Create Event Page". Is this correct or am I mistaken?

**Comment by GittiHab** [comment]
Why can't I view tournaments anymore? Is this because of this user story?
<img width="1710" alt="screen shot 2018-01-06 at 12 46 31" src="https://user-images.githubusercontent.com/6453623/34639423-6c8796a4-f2e0-11e7-8bcf-141711b5b5c0.png">
<img width="1710" alt="screen shot 2018-01-06 at 12 46 28" src="https://user-images.githubusercontent.com/6453623/34639424-6ca7c352-f2e0-11e7-9182-d4de31c6702d.png">

**Comment by GittiHab** [comment]
The bug does not seem to be caused by this user story, so I will accept it.
