### ISSUE TITLE
Create Sample User Data

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#234]
AS a logged in User
I WANT TO see some sample users who are already in the system per default
TO play with the system and try out its functionality

ACCEPTANCE CRITERIA
- [ ] Every time the system is refreshed I want to have 10 default users configured per script
      - [ ] They should have normal realistic names and attributes filled out
           - First Name
           - Last Name
           - EMail 
           - Birthday
           - Telefon Number
           - Favorite Sports
           - If no big overhead a profile picture
(If to difficult to come up with people than use http://de.fakenamegenerator.com/gen-random-gr-gr.php)

**Comment by nikriek** [comment]
Actual complexity of 3
