### ISSUE TITLE
Create Event model wiki page

### ISSUE THREAD

**Issue by Askir** [hpi-swt2/sport-portal#239]
Create an event model wiki page explaining STI. So other teams know how to use the event model and create pages and new functionality correctly.

**Comment by Askir** [comment]
https://github.com/hpi-swt2/sport-portal/wiki/Das-Event-Model
Done!

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by Askir** [comment]
actual size: M
