### ISSUE TITLE
show only relevant data in detailed event page

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#244]
**As a** event-member 
**I want to** see only relevant data on the detailed event page
**In order to** have a better overview

Acceptance Criteria:
 - [x] "Spielsystem" displayed correctly
 - [x] "Eventtyp" shown (e.g. Turnier) in the headline
 - [x] Single/Team (+ Team size if team)
- [ ] Anzahl Teams should not show nothing (better is "unbegrenzt") if no number was  given
Demo picture:
![eventpage](https://user-images.githubusercontent.com/8302493/33952899-7c263314-e033-11e7-918f-f5557547b37a.png)

**Comment by GittiHab** [comment]
Please don't forget to also have a specific site for ranking lists
