### ISSUE TITLE
Doubled "Leave Team" button

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#248]
User doesn't see the button "Aus dem Team entfernen" in front of his name. To leave a team he clicks the button "Team verlassen".

![sport-portal](https://user-images.githubusercontent.com/27727717/33881948-c5f7cf64-df36-11e7-8b69-a2c90997495c.png)

**Comment by lheilmann** [comment]
**Development Tasks**

- [x] Add test for appearance of delete membership button for current user
- [x] Delete the button „Aus dem Team entfernen" for current user in `show.html.erb`
