### ISSUE TITLE
Button "Team verlassen" is visible only for team members

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#249]
If user is not a member of a team, he doesn't see the button "Team verlassen".

![sport-portal](https://user-images.githubusercontent.com/27727717/33882348-139f85f8-df38-11e7-8e75-92d7ff8e60c5.png)

**Comment by lheilmann** [comment]
**Development Tasks**

- [x] Add test for appearance of button „Team verlassen" depending on user has a team membership or not
- [x] Delete the button if current user has no team membership for current selected team
