### ISSUE TITLE
Filtering table "Teams"

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#253]
As User I can pick only my teams in the overall teams' table so I don't need to search for them. 

Acceptance criteria

- Dropdown with possibility to choose either all or my teams

<img width="711" alt="screen shot 2017-12-12 at 18 59 20" src="https://user-images.githubusercontent.com/27727717/33900423-9b304a62-df6e-11e7-941e-7e8c619f238a.png">

**Comment by niconomaa** [comment]
- [x] write view tests to check for presence of dropdown
- [x] write controller tests to check on effective filtering of teams 
- add dropdown to view
- send dropdown selection to controller
    - [this](https://stackoverflow.com/questions/9280651/how-can-i-pass-the-selected-value-from-a-drop-down-list-to-the-controller-in-rub) might be of help
- make controller return filtered entries if so desired
    - [this](http://guides.rubyonrails.org/active_record_querying.html#scopes) specifies `scope`, which might be handy
