### ISSUE TITLE
Text for Landing Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#255]
We need to write text for Landing page that describes functionality of platform, features and advantages of platform.

Volume of text is the same (plus/minus 20%) as in mockup. You can find all information in attached PDF's.

- Text has to be unique;
- Keep sentence short and simple;
- Focus on the action (sign-up and try platform);
- Text has to be written in good german;
- Headlines stay the same --> Nope

**Estimation: M (Actual: M)**
 
![sms_01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fb99891cd2d2ebc3abaf51ab57f5973d047d317c05f3782387e72aba1579545f594eac42515a10adfbd82db4aa2e32db025fb28c341521842f1bbeb98a15be04bb238a4787b6be884bc8ee2f68.png)
 

[sport-portal.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fb84953196ceb980fbab42a81fbcd6395428792c07b7692ac7b629ef1128030b0d1bab135d5f42fcf98a22a3e26d72db5a19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bd894dc8ea3e22e08d86472c53.pdf)
[SportManagementSystem_PO.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db84953196aea881e8b846a958fe801a5f34672c099c1b5fc7af6aaf50740b0a0c0abe4b4a5a15fcfa8a79f2e46977d8590bebd16d5c7dc36940aee9840da313f871d51bdaebe5c01982fa3737e58b854e3b1f061981fc5c30a69b4dc14abb.pdf)

**Comment by jcremerius** [comment]
TODO:
- [x] Turnierplanung für Fußball und Co.
- [x] Kinderleichte Turnierverwaltung
- [x] Anwendungsbereich
- [x] Spielpläne im Überblick
- [x] Über uns

**Comment by MariusDanner** [comment]
@zhamanakov We want to be part of the imprint :)

**Comment by MariusDanner** [comment]
Please Review @zhamanakov 

https://docs.google.com/document/d/14_6c6GvXVsSDL6H7DpSHyd1ui4MGrMmkwmhB3gvKCl4/edit?usp=sharing

**Comment by jkbe** [comment]
@jcremerius @MariusDanner can you please "implement" the changes as requested by Dima?

**Comment by jkbe** [comment]
What's the status here @jcremerius @MariusDanner?

**Comment by MariusDanner** [comment]
@jak-ing Finished
