### ISSUE TITLE
Style Imprint Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#256]
Design of static Impressum Page as shown in mockup.
- Header is not part of this user story  (header is the same (see #183));
- we implement only h1 and text styling;
- Maximum width of content: 1200px (what selector to use here so that everything is restricted?)
- FONT: ProximaNova
- logos at the bottom are not for us
- mock imprint text is also part of this story, see zip file
 

![Screen Shot 2017-12-13 at 18.06.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f06b7191a379e70c2b57415a48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf743e44d55a1153e64f43b.png)
 
![Screen Shot 2017-12-13 at 18.07.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f06b7191a379e70c2b56415f47be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95bf743e44d56a7153666f43b.png)
[impressum.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46e1998a318790ba9ae4fd0fe64de29b234324676b5ee17e71d5b07bbd467904580d4bac47585f47f5fcdd7aa4e73a62964e49bc8f3900299f7744eeaa880dbe06b0218e4e86b7b48c45c0e13f27e499c2.zip)

**Comment by jkbe** [comment]
**Estimation: XS (Actual: S)**

**Comment by jkbe** [comment]
Essentially done, waiting for #185 to be merged.
