### ISSUE TITLE
Printable playing schedule

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#262]
As league/tournament organizer/participant 
I want to print the playing schedule of my event
In order to have an offline version of the schedule and check it out on the pitch.

**Acceptance Criteria**

- [ ] the playing schedule should be easily printable
- [ ] it should not look like you have printed the website

**Hint**

choose the simplest way possible, pdf export may not be necessary, just hiding the sidebar etc. for printing would be sufficient

**Comment by usame-algan** [comment]
Should the buttons ("Anzeigen", "Bearbeiten", "Löschen") inside the schedule table be visible when printing?

**Comment by MarcelSchmidberger** [comment]
there will be some changes that remove some of the buttons anyway, as stated here https://github.com/hpi-swt2/sport-portal/issues/300
but it would be awesome if you could remove the remaining button
please estimate the necessary effort

**Comment by usame-algan** [comment]
Actual size: XS
