### ISSUE TITLE
Bad alignment of text and textfields with some aspect ratios of the site

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#278]
![image](https://user-images.githubusercontent.com/29160369/34337929-e4db6f30-e963-11e7-9150-d126adf1b1b4.png)

![image](https://user-images.githubusercontent.com/29160369/34337935-f182e362-e963-11e7-9538-27664b4a1ea2.png)

**Comment by GittiHab** [comment]
This is not really a bug, maybe we can transform this into a proper user story regarding the design/mobile layout?

**Comment by MarcelSchmidberger** [comment]
solved
