### ISSUE TITLE
group related fields in create league form

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#279]
As creator of an event/league
I want related input fields to be grouped together
In order to help me understand the creation process better

**Group fields:**

Basisinformationen
- Name, Beschreibung, Sportart, Spielsystem

Teilnehmer
- Teilnahmeform, Anzahl Teams

Termine
- Dauer eines Spieltages
- Anmeldefrist, Beginn, Ende

**There may be changes after customer feedback.**

**Comment by MarcelSchmidberger** [comment]
a new field was added to leagues and tournaments: "Auswahlverfahren" this should be shown in the group of "Teilnehmer" as the last entry. And just to reiterate what was said in the meeting: The exact order is not so important its in gerneral about a sensible grouping and if changes in the order make it easier to code, please tell me about it.

**Comment by usame-algan** [comment]
Actual size: S
