### ISSUE TITLE
viewing tournaments not possible

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#288]
When trying to enter a tournaments detailed page (e.g. from the new event page as seen below or from the events overview page) I always receive an error.
<img width="1710" alt="screen shot 2018-01-06 at 12 46 31" src="https://user-images.githubusercontent.com/6453623/34639429-8f8a7cfc-f2e0-11e7-8e89-ae02fd31f03a.png">
<img width="1710" alt="screen shot 2018-01-06 at 12 46 28" src="https://user-images.githubusercontent.com/6453623/34639430-8fa9c7f6-f2e0-11e7-8a60-d16c1b4b1c15.png">

**Comment by MerlindlH** [comment]
creating tournaments is still possible, but entering a tournament event page isn't...

**Comment by GittiHab** [comment]
This seems to be fixed.
