### ISSUE TITLE
Date changes for playing days

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#295]
As league/tournament organizer
I want to be able to reschedule(change dates) of my playing days
In Order to let the participants play whenever they have time to do so.

**Acceptance Criteria**

- [ ] date fields for playing day are editable and there is an edit button 

**Out of Scope**
* it is not necessary, to update the dates of following playing days (please consider the effort needed for this any contact me if you think it would not be to difficult)

**Mockup**

![image](https://user-images.githubusercontent.com/29160369/34922668-64445b26-f993-11e7-96c1-1d3734e8c308.png)

**Comment by Askir** [comment]
actual size: XXL already and it's not even merged :sweat_smile:

**Comment by MarcelSchmidberger** [comment]
The following changes are requested:

### Correct date of gameday should be shown in the matches:

![image](https://user-images.githubusercontent.com/29160369/35591930-ceabde56-060b-11e8-90fd-a027790d653b.png)

- [ ] The gameday number and the correct timespan of the gameday should be displayed
