### ISSUE TITLE
Notifications for user: email settings

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#301]
As _User_ I want to be _informed_ about changes in my _events, teams or event calendar_ to plan my participation accordingly. 

**Acceptance criteria**

- Notification is an automated email sent to the mailbox of the user
- Only registered users can receive notifications
- Emails can be turned on/off on the page "Benachrichtigungseinstellungen". By default notifications are turned on. 

![pasted_image_17_01_18__14_23](https://user-images.githubusercontent.com/27727717/35044824-0f84d2e0-fb92-11e7-88cb-3cd7b1e070f6.png)

**Important**
Check issues #57 and #149 and communicate with other dev teams

**Out of scope**
Implementation of notifications on the website should not be done.

**Comment by lheilmann** [comment]
@svitlanakalancha Size of "Send mails in rails applications" (Spike):  5

**Comment by lheilmann** [comment]
@svitlanakalancha Size of "Research on jobs on rails server targeting event emails - see #301" (Spike): 5

**Comment by lheilmann** [comment]
Checkbox "Newsletter abonnieren" is out of scope. Cheers.

**Comment by lheilmann** [comment]
Result of checkboxes is stored in database flags.

**Comment by lheilmann** [comment]
**Mockup update:**
- [ ] Team notifications
- [ ] Event notifications

**Comment by birneamstiel** [comment]
@tomkellog @conradlempert I've agreed with @bakoe on how to name those flags: `team_notifications_enabled` and `event_notifications_enabled`

(see [here](https://stackoverflow.com/a/37060624) for detailed explanation)

**Comment by birneamstiel** [comment]
time needed: 3.5 h
