### ISSUE TITLE
Spike: triggering emails on the platform

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#306]
The system should automatically inform a user about changes in his event calendar or his team list. For example, if user participates in some event and new match against his opponent is scheduled, the user receives an automated notification in form of an email. These events connected to the user should be observed in order to send automated notifications.

The goal of the spike is to research jobs on rails server to target relevant events.

See #301, #307, #308 

**Important**
Check issues #57 and #149 and communicate with other dev teams

**Comment by niconomaa** [comment]
### events on model changes
* [this guide](http://guides.rubyonrails.org/active_record_callbacks.html) describes `Active Record Callbacks` which are functions that can be triggered during the lifecycle of an object (such as `after_save`, `before_update` ...)
* we might use these to notify users when their events, matches and teams are created, changed or deleted
* a callback that notifies a user that he's been added to a team might be implemented like this in the `TeamUser` model:
```
  after_create :notify_member
 
  def notify_member
    puts 'Hey ' + User.find(self.user_id).first_name + ", you are part of the team now!"
  end 
```
### timed events
* [this guide](http://edgeguides.rubyonrails.org/active_job_basics.html) desribes `Active Job`s which are classes that perform an action at a certain time
* we might use these to notify members about a the start or end of a match and similar use cases
* an `Active Job` that notigies users that their match is happening now might look like this:
```
class NotifyUserJob < ApplicationJob
  queue_as :default

  def perform(user)
    puts User.find(user).first_name + " your match is NOW!"
  end
end

```
* and to schedule the job we might do:
```
after_create :queue_member_notification

def queue_member_notification
   NotifyUserJob.set(wait: 15.seconds).perform_later(User.first.id)
end
```

**Comment by lheilmann** [comment]
@tomkellog Is this working with Heroku installations? Have you researched on that?

**Comment by lheilmann** [comment]
@tomkellog What about explicit times, e.g. 2018-01-20 1PM? We can't find it in your second example.

edit by tomkellog:
works as well
