### ISSUE TITLE
Notifications: events/matches

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#308]
As User I want to be informed about changes in my events to plan my matches accordingly.

**Acceptance criteria**
- general requirements see #301 
- emails are automatically generated when triggered
- the text of emails is predefined and includes placeholders for customization (see texts below)

Triggers are:
- a match where user participates is scheduled

> Hallo _user name_,
> dein Spiel gegen _oponent team_ in _event name_ findet am _datum_ statt.
> Viel Erfolg beim Training!
> _Link to the event_

- a match where user participates is cancelled or postponed

> Hallo _user name_,
> dein Spiel gegen _oponent team_ in _event name_ wurde (auf  _datum_ verschoben / abgesagt).
> Viel Erfolg beim Training!
> _Link to the event_

- an event where user is registered is started/cancelled/finished

> Hallo _user name_,
> das Event _event name_ hat gestartet (ist abgesagt/ ist abgeschlossen).
> Viel Erfolg beim Training!
> _Link to the event_

**Important**
Check issues #57 and #149 and communicate with other dev teams

**Comment by niconomaa** [comment]
### triggering actions based on model events
* [this page](http://guides.rubyonrails.org/active_record_callbacks.html) describes Active Record Callbacks, which are methods that can be triggered on several model events such as delete, create and update
* for events such as de deletion or creation of a match a user participated in, these callbacks can be used to notify the user
* in the model at hand a callback may be implemented like this:
```
  after_create :notify_about_member
 
  def notify_about_member
    puts 'Hey ' + User.find(self.user_id).first_name + ", you are part of the team now!"
  end
```
### triggering actions at certain times
* [this page](http://edgeguides.rubyonrails.org/active_job_basics.html) describes Active Jobs, which are a class in Rails that define jobs to be executed at a certain time
* combining Active Record Callbacks with Active Jobs, we could, for instance, schedule jobs when each match is created for the time in happens, notifying the members of each team that participats int the match about it
* a job that notifies a given member about his or her match might be implemented like so:
```
class NotifyUserJob < ApplicationJob
  queue_as :default

  def perform(user)
    puts User.find(user).first_name + " your match is NOW!"
  end
end
```
* and a method in a model that schedules the job might look like this:
```
    # SPIKE
    after_create :queue_member_notification
 
    def queue_member_notification
      NotifyUserJob.set(wait: 15.seconds).perform_later(User.first.id)
    end
```

**Comment by lheilmann** [comment]
@tomkellog You probably need to check, if the Heroku installation/VM "sleeps" while nobody sends a request. I think you will notice that, when you first deploy and test your results on one installation. For such cases we offer a third installation next to `dev` and `production`, where you can deploy one branch/pr. You then can see how your application behaves in production mode. Please talk to me,  when you reached that state in development, where you want to deploy to heroku.

**Comment by bakoe** [comment]
@tomkellog @conradlempert I noticed that in #267 (PR not merged yet) an ApplicationMailer as well as a corresponding MatchMailer has already been introduced. Maybe we should build up on that?

**Comment by lheilmann** [comment]
@conradlempert Please add reference to your commit messages to see a complete listing of commits related to this issue. Did you know there is a [Cheatsheet](https://github.com/hpi-swt2/sport-portal/wiki/Cheatsheet) to collect information about desired branch naming, etc.? 😉
