### ISSUE TITLE
Show player's profile in the team table

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#334]
As User I can **open profiles** of other players **by clicking** on their names in **the team list** to know with whom I play. 

**Acceptance criteria**
- Name of the player on the team list should be clickable for all registered viewers
- Signed off/ not registered viewers can't see players' profiles
- By clicking on player's name viewer lands on personal profile of chosen player
- Names on the team page are clickable and visible (Open Teams page -> choose some team -> go to its page -> players in team table)

See an example of players list in the event (Events -> Any event with applied users)

<img width="435" alt="screen_shot_2018-01-14_at_19_15_28" src="https://user-images.githubusercontent.com/27727717/34919181-81d554ee-f95f-11e7-99fb-56defccff94e.png">

Click results in:

<img width="469" alt="sport-portal" src="https://user-images.githubusercontent.com/27727717/34919198-9ec4d1ce-f95f-11e7-9739-b40d48a5253f.png">

**Comment by jonasnoki** [comment]
![image](https://user-images.githubusercontent.com/17072869/35447179-518f16e2-02b7-11e8-87c3-2f4f86c3f7eb.png)
Welcher Teil des Namens soll geklickt werden können? @svitlanakalancha

**Comment by svitlanakalancha** [comment]
@jonasnoki lass uns den Vornamen nehmen. 
Können wir eigentlich die Spalten auch Vorname, Nachname umbennen? Ist mir gerade aufgefallen, dass sie auf Englisch sind

**Comment by jonasnoki** [comment]
Needed time: 2h
