### ISSUE TITLE
Team page: applying action without checkboxes results in error

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#338]
If user tries to perform team action (assign/delete captain or kick from the team) without choosing affected persons, app crashes.

**Actual behaviour**
- Go to **Teams** page and create your team.
- Without applying checkboxes click assign/delete captain or kick somebody from the team
- **Result: app crashes**

**Correct behaviour**
- Buttons are not shown until the user chooses some player/s. 

<img width="1099" alt="sport-portal" src="https://user-images.githubusercontent.com/27727717/34919788-e7e14a1e-f968-11e7-86bc-36e61acc17d5.png">

**Comment by lheilmann** [comment]
Buttons should not be visible, when no checkbox is enabled.

**Comment by jkbe** [comment]
Checkboxes are not shown right now (#396) and so no participant can be selected on dev at the moment. We need this to implemented for #381. What's the status about this?

**Comment by jkbe** [comment]
Edit: As #381 is not part of our current sprint backlog, we are not depending on this bugfix right now but would be nice to have in 1-2 weeks. :)
Edit of Edit: We started work on #381 and will fix the invisible checkbox described by me above (addressed in #396).

**Comment by jkbe** [comment]
However, we will not fix this issue #338 as responsibility for this seems to be with Team Kickerz.

**Comment by bakoe** [comment]
Actual time I invested in this issue: 1 h 10 min
