### ISSUE TITLE
League page: delete "Übersicht" button

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#339]
**Übersicht** button should be deleted from the league page.

**Acceptance criteria**
- The button should be deleted **ONLY** from league page
- The list of participants should be shown on the ranking page

<img width="537" alt="sport-portal" src="https://user-images.githubusercontent.com/27727717/34919898-5806d5a6-f96a-11e7-96b0-3f288e82e55c.png">

**Comment by lheilmann** [comment]
Delete route & view for overview page.

**Comment by birneamstiel** [comment]
needed-time: 3h
