### ISSUE TITLE
Only current events should appear on the "all events" page

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#34]
**AS AN** user
**I WANT TO** see only events where the deadline for signing up has not passed yet when viewing the *all events* page
**SO THAT** I don't get confused about which events I can sign up for

## ACCEPTANCE CRITERIA
- [x] when opening the *all events* page only events where it is still possible to sign up should be displayed by default

**Comment by GittiHab** [comment]
Reviewed and accepted by Product Owner
