### ISSUE TITLE
Hide buttons for ranking lists

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#351]
**AS A** viewer of a ranking list event
**I WANT TO** not see the "playing schedule" and "overview" button

## ACCEPTANCE CRITERIA
- [ ] When viewing a ranking list event, the playing schedule button should be hidden
- [ ] When viewing a ranking list event, the overview button should be hidden (the table behind that is another one, described in #135)

**Comment by GittiHab** [comment]
A new button "Table" was added by another team and is still visible... can we also remove that one?
<img width="190" alt="screen shot 2018-01-26 at 10 25 57" src="https://user-images.githubusercontent.com/6453623/35433346-6a801e50-0283-11e8-8357-fb100f5317c7.png">

**Comment by jonasnoki** [comment]
As part of issue  #125 I also have to remove the button you are talking about. I was also requestet to remove the route. What's your progress on this?

**Comment by pawelsoundso** [comment]
I have completed the task on hiding the button for ranking lists, but not yet merged it. I guess you have to hide it completely for every or other type(s) of events, so I'm fine if we ignore my changes and you make sure to include the functionality itself in your branch.

**Comment by jonasnoki** [comment]
That sounds good.

**Comment by GittiHab** [comment]
This is handled in #125 so we can close this issue.
