### ISSUE TITLE
New name of project

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#364]
New name of project is "SPORTIFY".
This name should be placed on every page in top right corner with logo. 

Like this:

![Screen Shot 2018-01-16 at 19.06.46.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f56b7191a379e60c2b57415b48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef749e74d5cad123e67f43b.png)

The font is the same.
The font-size is 26px. 
"SPORTIFY" should be written with capital letters (no need to use graphics)

**Comment by jkbe** [comment]
@zhamanakov please provide arrow graphic without any background or project name text

**Comment by jkbe** [comment]
**Estimation: XS (Actual: S)**

**Comment by stursberg** [comment]
![sportify_logo](https://user-images.githubusercontent.com/15203334/35141104-1a490fb6-fcfa-11e7-9ce8-c99461c7692f.png)

**Comment by jkbe** [comment]
@zhamanakov I'll replace it in the footer as well, right?

**Comment by stursberg** [comment]
@jak-ing yes
