### ISSUE TITLE
Extract ranking logic into dedicated class

### ISSUE THREAD

**Issue by birneamstiel** [hpi-swt2/sport-portal#367]
Make the `EventsController` slim again by moving logic calculating the ranking logic into new Class (something like `RankingEntry` and `RankingList`). The `Event` model would probably have a `#get_ranking` method that would calculate the ranking list.

- follow-up for #125
- see https://github.com/hpi-swt2/sport-portal/pull/286#discussion_r161774881

**Comment by erksch** [comment]
Whats the status of this? I need the extracted ranking method to implement the swiss system.

**Comment by birneamstiel** [comment]
@erksch I'd say you have a look at the PR referenced above :-)

https://github.com/hpi-swt2/sport-portal/pull/419

**Comment by birneamstiel** [comment]
needed time: 4h
