### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#37]
- #As logged in User 
- #IWantTo configure my profile 
- #To
  - store and see my personal data
- #AcceptanceCriteria
 - [ ] When hovering on my profile name on the top right corner I get a dropdown menu which contains an item  "Abmelden",
When I click on "Abmelden" then I want to get logged out which substitutes the button sign out on the top right corner

**Comment by jkbe** [comment]
Would be cool if you could tell @deeps96 and @jcremerius when this is merged because they depend on the user dropdown menu for #45.

**Comment by manner** [comment]
Estimated Size: 3
Actual Size: 4
