### ISSUE TITLE
Admin can edit all events

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#371]
As an Admin
I want to be able to edit all events
In order to maintain them and adjust them if necessary

right know permission is denied when the admin wants to edit an event he did not create
![image](https://user-images.githubusercontent.com/29160369/35040069-23916c92-fb80-11e7-999e-3d1e0eef6fec.png)

**Acceptance Criteria**

- [ ] admin can edit all events and therefore has the same rights as the organizer for each event

**Comment by jkbe** [comment]
**Estimation: M**

**Comment by jkbe** [comment]
@zhamanakov please test on dev.

**Comment by stursberg** [comment]
Everything ok!
