### ISSUE TITLE
Working "back"-buttons

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#375]
**As a user** of the platform
**I want to** have intuitively working "back"-buttons
**In order to** navigate the platform easily.

## Acceptance Criteria:
 * It should be possible to get back from every subpage to its parent page without detours
    * example: event schedules and overview pages have no back button
 * Existing "back"-Buttons should refer to the expected page not the last visited page
    * example: Try editing an event and then clicking on back, currently you come back to the editing page but you should get back to the all events page
 * If you are not sure what the right page for referring to is, ask your PO :D

### Notes:
 * mentioned as bug #158 
 * It's probably wise to find a solution that works for all pages and does not require you to enter this data on every single page manually

**Comment by emanuel-metzenthin** [comment]
I'm asking again: Could you PLEASE rename your branch? The "" are still causing problems for many devs.
