### ISSUE TITLE
Priority for OPEN-ID

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#377]
A small layout change for SIGN-IN page (only replacement of "Anmelden mit OPEN-ID" link + small design changes)

Register button in mobile version should not be added/changed.

![Screen Shot 2018-01-17 at 14.39.51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f46b7191a379eb0c2858415a4fbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef742e7495dac173463f43b.png)

![Screen Shot 2018-01-17 at 14.43.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f46b7191a379eb0c2f52415f4cbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95ef742e74b55a4113263f43b.png)

Background, header, footer etc here are out of scope!

**Comment by jkbe** [comment]
**Estimation: XS (Actual: XS)**
