### ISSUE TITLE
'Create Event' Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#378]
**#365 and #374 depend on this for card component**

Now "Create event" page looks not so nice:

Make sure to reuse stuff from #182.

Tasks:
- [x] Make extra `.erb` for the 'card design' which can be reused in #365
- [x] fill with content

![Screen Shot 2018-01-17 at 15.02.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f46b7191a379ea0c2b53415c4cbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef742e64457a516346af43b.png)

New design for this page:

![event_desk.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ed829f2d96bcad8afab401e81fe086264c22703d46f9692584b37bec407f030a581ca9415e5f44fff08c7ff7b46d76984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b0bd834bc9e13a24ef8e9d02.png)

Header and footer are out of scope.
Content from card in picture is correct! 

Mobile Version:

![Screen Shot 2018-01-17 at 15.14.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f46b7191a379ea0c2a55415f4cbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef742e94950a6163f62f43b.png)

**Comment by jkbe** [comment]
**Estimation: M (Actual: S)**

**Comment by jonashering** [comment]
Ready, but waiting for PO feedback.

Edit: PO approved sent screenshots

**Comment by jonashering** [comment]
Integrating PO's feedback on design issues and falsely used texts.
