### ISSUE TITLE
Profile Properties

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#38]
- #As logged in User
- #IWantTo add general information about myself
- #To 
  - give other people more information about me
  - give other people the chance to contact me
- #AcceptanceCriteria 
  - On the profile page, I want to see all of my personal data which are directly editable
    - [ ] Birthday 
      - I should be a able to edit my birthday with the Label Geburtstag
    - [ ] Telephone
      - I should be able to edit my telephone number with the Label Telefon
    - [ ] Telegram
      - I should be able to edit my telegram username with the Label Telegram Username and the telegram icon https://commons.wikimedia.org/wiki/File:Telegram_logo.svg
    - [ ] Favorite Sports
      - I should be able to indicate my favorite sports in a field with the label Lieblingssportarten
        - An example of "Fussball, Basketball, Tischkicker" should be given as a suggestion
  -I want to have a drop-down menu item on the top right corner called "Mein Profil"

**Comment by manner** [comment]
assigned to: Erik
