### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#39]
- #As logged in User 
- #IWantTo have a profile picture 
- #To
  - be quickly identified in player lists
  - to have a more personal touch
  - to get a personal touch
- #AcceptanceCriteria 
  - [ ] I can upload the profile picture on my profile page
    - The picture should not be larger than 2MB
    - A default picture should be shown which should be free to use when I haven't set a profile picture
  - [x] I want to see my profile picture next to my name when I am logged on on top right corner

**Comment by nikriek** [comment]
Actual complexity of 40
