### ISSUE TITLE
Checkboxes on teams show page are hidden

### ISSUE THREAD

**Issue by lheilmann** [hpi-swt2/sport-portal#396]
![screen shot 2018-01-18 at 17 31 50](https://user-images.githubusercontent.com/18228544/35109063-8f387f76-fc75-11e7-8d61-49548abf24cc.png)

Checkboxes are not visibile anymore after redesign was applied. 

Checkboxes are hidden, because of a missing label. Fancy checkboxes are appended as :before element to the corresponding label, that is missing. No label, no fancy checkbox!

Following code hides default checkboxes:

```
/* Remove default checkbox */
[type="checkbox"]:not(:checked),
[type="checkbox"]:checked {
  position: absolute;
  /* opacity: 0; */
  pointer-events: none;
  }
``` 

To bring back our lovely checkboxes, we  need to label them. :+1:

**Comment by lheilmann** [comment]
@hpi-swt2/team-sk-17 @svitlanakalancha and me decided to fix this bug in the current sprint, because of high priority! Does anybody feel comfortable with fixing this bug in the current sprint? I suggest the following workflow, according to scrum processes:
 
- We estimate the effort this issue as soon as possible. No need to estimate together will all team members - SM and developer will last.
- Issue gets assigned to a developer.
- Issue will be placed in sprint backlog with high priority.
- Developer will implement issue in current sprint as soon as possible, according to priority.
- Developer will implement other assigned issues in current sprint, as long as she/he will stay in personal sprint velocity. If other issues cannot be implemented, because personal velocity is reached, these issues stay in sprint backlog and will be implemented next sprint.

Everybody cool with this workflow? Additions?

Hang loose.

**Comment by jkbe** [comment]
CSS definition comes from Materialize: https://github.com/Dogfalo/materialize/blob/36940460f1d805ec0b721302e68c500592f37b13/dist/css/materialize.css#L6752

**Comment by lheilmann** [comment]
After talking to @jak-ing we decided to implement this issue in the current sprint by team Flexibus.

**Comment by jkbe** [comment]
This will be part of #381, there won't be a separate PR.

**Comment by lheilmann** [comment]
Alright! Please then reference this issue in the upcoming PR.

**Comment by jkbe** [comment]
Is being reviewed in PR #465 as part of Issue #381
