### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#40]
- #As logged in User
- #IWantTo access my profile settings over the menu
- #To 
  - Have a uniform access to all my account properties
- #AcceptanceCriteria 
  - [x] When clicking on "Mein Account" on the menu on the top right corner I can see a page with
    - my E-mail
    - my Name
    - my changing my passwort
      - Current Password
      - New Password 
      - Confirmation New Password

**Comment by manner** [comment]
assigned to: Lariiii
