### ISSUE TITLE
Notification Settings

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#41]
Notification Settings

- #As logged in User
- #IWantTo change my notification settings
- #To 
  - be able to control how many notifications I get on the portal
  - be able to control for what I get E-Mail notifications
- #AcceptanceCriteria 
  - [ ] I want to have a dropdown menu item called "Benachrichtigungseinstellungen" which links to an empty page

**Comment by manner** [comment]
assigned to: Melvin

**Comment by Lariiii** [comment]
Actual complexity: 2
