### ISSUE TITLE
Log-in Button

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#42]
AS a user
I WANT to separate main-menu and log-in button visually (log-in button further to the right)
SO THAT I can find this button quickly

![Screen Shot 2017-11-13 at 11.15.01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f06b7191a379ee0c2a54415f4fbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec958f34de94c57a6143766f43b.png)

Acceptance Criteria:
- there is button "Einloggen", that visually separated from the main menu
- there in no second button "Sign up"
- klick on this button redirect user to page "sign-in"

**Comment by zhamanakov** [comment]
test

**Comment by jkbe** [comment]
#### Estimation: S
#### Actual Size: M (with sidequest i18n that came up when working on this issue)

**Comment by jkbe** [comment]
Tip: Passing `fluid: true` to `<%= nav_bar ...` could help keep navbar content from overflowing when aligning it to the right (see https://github.com/hpi-swt2/sport-portal/commit/fb4e8a602a5accf8e0fa4ba19f744041715aa3de#diff-bdc5ec11de297c778fc5578eb85d88bcR2)
