### ISSUE TITLE
Log-in Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#43]
AS a user
I WANT to have possibility to create an account
SO THAT I can use sport portal

![Screen Shot 2017-11-13 at 11.29.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f06b7191a379ee0c2958415e4fbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec958f34de94453ac143561f43b.png)

- Interface of sign-in page should look like on the mockup above (layout, texts, design doesn't matter)
- Link "Registrieren" redirect user to page "sign-up"

**Comment by jkbe** [comment]
#### Estimation: S
#### Actual Size: S

#### Notes
Keep 'remember me' button as is.
