### ISSUE TITLE
Button "Einloggen" für "Eingeloggten"

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#44]
AS a logged-in user
I WANT not to see the button "Einloggen" anymore, but to see my name and my profile pic
IN ORDER TO know, what account do I use in a moment, and to access user-menu
![Screen Shot 2017-11-13 at 11.51.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f06b7191a379ee0c2e50415f4cbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec958f34ce14e54a1173167f43b.png)

- We DO NOT implement user-menu. 
- There should be a placeholder for avatar
- We implement only drop-down menu (not links for 'settings' and 'profile') by click on user name AND functionality of button "Ausloggen".

**Comment by jkbe** [comment]
#### Estimation: M (Actual Size: not applicable because we didn't work on this)

**Comment by jkbe** [comment]
This User Story is redundant to #37.
