### ISSUE TITLE
create Form for event creation including error display and controllerAction

### ISSUE THREAD

**Issue by FJThiel** [hpi-swt2/sport-portal#48]
Part of user story #19 

The form for the model from #49

This form should display fields for:
- Name (mandatory)
- Beschreibung
- league or tournament (mandatory), pre-selected, but changeable
- Sportart (mandatory)
- Teams or Einzelsportler or none (will allow both)
- Maximale Anzahl der teilnehmenden Teams (nothing means no limit)
- Spielsystem (mandatory); please refer to #19 for details

the form should have two buttons:
- create : this creates a league with the given parameters
- cancel : this cancels the process and brings you back to the create event page

Should any errors arise by any operation they should be displayed

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by usame-algan** [comment]
Actual size: S
