### ISSUE TITLE
translate profile creation errors to german

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#485]
**As a** german user
**I want to** have german error messages while editing profile data
**In order to** unterstand the error messages I get while editing

### notes:
 * was part of #369 

## Acceptance Criteria
* [x] please germanize all Error messages, e.g. "Birthday Der Geburtstag darf nicht in der Zukunft liegen" or (2) or (3) 
* [x] please translate the Choose file / no file chosen (visible in (1)) as well

### pictures:
(1)
 ![image](https://user-images.githubusercontent.com/8302493/35038387-fab1f512-fb7a-11e7-97b7-2be371be1f8c.png)
(2)
![image](https://user-images.githubusercontent.com/8302493/35038349-d9abb9e8-fb7a-11e7-832c-06efec47e265.png)
(3)
![image](https://user-images.githubusercontent.com/8302493/35039152-453def80-fb7d-11e7-9bd1-7a330bd638bd.png)

**Comment by fpottbaecker** [comment]
Checked second criterion: Text is handled by Browser

**Comment by MerlindlH** [comment]
:+1:
