### ISSUE TITLE
Single Players should not be shown in Teams

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#488]
This bug is caused by the other bug, namely: if a single user joins some event, the team with only this user is automatically created. This "team" will be shown then on the teams' list.

**Correct behavior**
Single player teams should **not be shown** on the `Teams` page.

**Comment by birneamstiel** [comment]
only on index page, no change on email logic

**Comment by niconomaa** [comment]
#assi
