### ISSUE TITLE
create Model for events

### ISSUE THREAD

**Issue by FJThiel** [hpi-swt2/sport-portal#49]
Part of user story #19 

The model used by the create-event page from #48 

It should accept the following data:
- Name (mandatory)
- Beschreibung
- league or tournament (mandatory)
- Sportart (mandatory)
- Teams or Einzelsportler or none (will allow both)
- Maximale Anzahl der teilnehmenden Teams (nothing means no limit)
- Spielsystem (mandatory); please refer to #19 for details

Data flagged as mandatory should be validated. If one or more values is missing or invalid it should not be possible to create the event and an error is returned.

Every event should be identified by an unique id tha tis automatically assigned.

By creating the event the user is remarked as organizer of this event

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.
