### ISSUE TITLE
Single player team should not receive team notifications

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#494]
This bug is caused by the other bug, namely: if a single user joins some event, the team with only this user is automatically created. This "team" should not receive team notifications.

**Comment by lheilmann** [comment]
**Development tasks:**
- [x] Add tests for team notifications in `spec/models/team_spec.rb` regarding single player teams
- [x] Implement checks before delivering notification mails to prevent single player teams to receive mails

**Comment by lheilmann** [comment]
@svitlanakalancha To summarize: Single player teams should not receive team notifications at all, but teams with 2 or more members should be able to receive team notifications as discussed in #307?

**Comment by svitlanakalancha** [comment]
@lheilmann The issue is not really about the number of players in the team. These teams created for single players who joined some event are not real teams: you can´t add other users there. It is kind of stable team with one player. These fake teams should not receive emails. But the team created in a normal way as a team should receive emails even if it consists of one player only. Hope it helps :)

**Comment by lheilmann** [comment]
@svitlanakalancha Alright! Thanks for clarification :+1: 

@pawelsoundso Hi Pawel! You were implementing the `single` column on teams a month ago right? I assume the intention was to allow single players to attend events as well, without changing the already built infrastructure completely. Hence you needed to create teams flagged with a boolean to distinguish between multi-player teams and single-player teams? Please tell me, if I understood something wrong. 

My question to you regarding this issue is the following: Are there any other usages of this flag `single` or is it only needed in your events infrastructure? If so, I would suggest to rename this flag from `single` to `created_by_event` (boolean as well). In my mind this would be a more precise name for the flag. Besides it is possible to figure out if a team contains only one player without having a extra column. 

Would appreciate to have you on board here. :+1:

**Comment by lheilmann** [comment]
@pawelsoundso I can do the resulting refactoring, if needed. :smile:

**Comment by lheilmann** [comment]
**Notes:**
- [x] Check #437 
- [x] Check #433 
- [x] Check #507

**Comment by pawelsoundso** [comment]
Hey! If I understood you correctly, your assumptions about the `single` flag are correct. 

The reason for this additional column was the differentiation between single-player teams (or those teams that are created by the event) and those teams with only one participant, which are still teams and not substitutes for players. These were my intentions, why I used the additional flag and not just a method, that returns all teams that have only one player.
As far as I know, this is only usage of the flag and I really like your suggested name change (we were really struggeling with finding a fitting name), so you have my "go-ahead" on this. 😄 
Be sure to change the `multiplayer` scope though as well, which is our way of excluding all these "fake teams" in the team evaluation for events on multiple cases. 

I hope I could answer the question, you were having. You can of course ask me for further opinions on your work later if you want. 😉

**Comment by lheilmann** [comment]
@pawelsoundso Okay cool! Thanks for your detailed comment! :+1: 

I will talk to the SM's first to be sure that no conflicts will appear when refactoring this issue.

I would like to request your review on this PR later.

**Comment by lheilmann** [comment]
@bakoe Ahoi! I am currently working on a fix regarding the second bug listed in your last comment in #307:

> Bugs noticed after deploying the feature to Heroku:
>
>- When a user creates a new team, a new TeamUser instance is automatically created for him. This causes a “You have been added to team …” e-mail to be sent which is nonsense in this context
>- When a single user joins an event, a “fake team” is created automatically, which also creates a new TeamUser instance. This leads to the sending of two e-mails: One for “You have been added to team …” (which is quite nonsense) and one for “your team … has joined the event …” (which is also rather nonsense regarding there is no real team which joined an event).
… This may need further clarification about how single-player “fake teams” should be handled regarding the e-mail notifications

 I was wondering if there is a need to test my implementation by deploying to heroku (particular PR-machine). I already tested everything locally as you described in #437. Is the mailer working as desired after your applied hotfix?

**Comment by bakoe** [comment]
@lheilmann Hey there! Yes, the mailer is working as desired on the Heroku-deployed environments—at least when GMX is not making any problems. 😉

Thus, it's sufficient to manually test your implementation locally (by looking at the console output of `rails s`) and by writing according rspec tests that check for `ActionMailer::Base.deliveries.length` not increasing when e. g. joining an event as a single player. 

If both of these (manual and automatic) tests succeed, I think it's pretty safe to assume that the mail delivery should work the same way on the Heroku-deployed environments. To my mind, @svitlanakalancha is going to do some manual acceptance-tests on the Heroku-deployed environment either way.

**Comment by lheilmann** [comment]
@bakoe Alright, great! I already checked the console output and implemented the according rspec tests, while looking at your tests implemented for #307. :smile_cat: 

Thanks for helping out! :+1:
