### ISSUE TITLE
Design Profile Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#497]
New design for Player Profile Page
(https://sport-portal-dev.herokuapp.com/users/XX/profile)

![profil1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46f88695258b8ff8cda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8316b500bf218c4b84b6b88a4bc6e03c37aa.png)

![profil2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46f88695258b8ffbcda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8316b500bf218c4b84b6b88b4ac9ea3e37aa.png)

Button "Profil bearbeiten" goes to https://sport-portal-dev.herokuapp.com/users/XX/edit

**Comment by jonashering** [comment]
@zhamanakov What font sizes did you use for the section headings and their content? 

---
Try 20px and 36px.

**Comment by stursberg** [comment]
@jonashering please delete button "ZURÜCK" from Player Profile Page

**Comment by jonashering** [comment]
Working back buttons on all child pages are apparently part of #375, and
were therefore also added to the user views. Do you want the profile page
to differ from the in #375 defined acceptance criteria? @zhamanakov

**Comment by stursberg** [comment]
It's ok!
