### ISSUE TITLE
Generate schedule

### ISSUE THREAD

**Issue by FJThiel** [hpi-swt2/sport-portal#50]
Part of user story #35 

Schedule is viewed by #51 

A schedule based on the events configuration should be generated.
It should consist of Matches (Spielpaarungen)
It should (for now) be assumed that the max count of permitted players is reached all the time and if not entered is some random number for testing (this will be changed as soon as it is possible to sign up for an event.
The Matches should be based on "jeder gegen jeden" for starters (later one more match making systems).
This should work for leagues, tournaments will be added later.

**Comment by Askir** [comment]
@laurenzse This task is somewhat dependent on Issue #49 (which you have signed up for). The method that is needed for this task, has to be implemented on the event model. I can however create a minimal version of the model for this task and then we just have to merge it later. In case I am the first one to commit the feature you might wanna get in touch with me if you have questions :) I can also just wait for you to be done and then do the merging myself though.

**Comment by laurenzse** [comment]
@Askir Sorry blocking your progress! I hope to get onto it this evening :)

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.
