### ISSUE TITLE
New Design for Info-Notifications

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#501]
Every Notification disappear automatically in 5 seconds. Or it can be closed through "X" button.

![Screen Shot 2018-01-31 at 17.05.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e80c2b54415c49be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ff24ae54556a410336bf43b.png)

![Screen Shot 2018-01-31 at 17.06.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e80c2b57415e4ebe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95ff24ae54556a41b3460f43b.png)

![Screen Shot 2018-01-31 at 17.05.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e80c2b54415f4abe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ff24ae54556ac173460f43b.png)

**Comment by stursberg** [comment]
Texts or colors of notification-background should NOT be changed (there are not only green color possible)

**Comment by jkbe** [comment]
I just did a small spike of this and it seems pretty easy except for getting the (i) icon in there because the notification element comes from bootstrap and doing more than styling woul require to redo the whole thing. Would it be fine to leave that icon out @zhamanakov?

**Comment by stursberg** [comment]
@jak-ing yes, it's ok!

**Comment by jkbe** [comment]
Work is done and temporarily deployed on sport-portal-pr on Heroku.

**Comment by stursberg** [comment]
Everything is ok, except of 1 small thing: pls make that notification stay in content max-width.

![Screen Shot 2018-02-05 at 22.23.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f66b7191a37aed0c2952415e46be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ffe4de44454a51a346bf43b.png)

**Comment by jkbe** [comment]
Hm, it should be in there, same issue as in #379.

**Comment by jkbe** [comment]
The problem is that the container the notification resides in doesn't event have a max-width because it's the landing page and we want the pictures to span the whole width of the page. I've also not been able to fix it quickly and cleanly. Waiting for #379.

**Comment by jkbe** [comment]
After discussion with Dima, notification positioning is alright as it is right now => trying to merge.
