### ISSUE TITLE
View for the schedule

### ISSUE THREAD

**Issue by FJThiel** [hpi-swt2/sport-portal#51]
Part of user story #35 

Should show the generated Schedule from #50 

The organizer of an event should be able to acces the schedule page.
It should display as a large table which shows the matches in following manner:
- Column for the "Spieltag"
- both player/team names (numbers as playholders for now if necessary)
- results; outcome of the match
- points depending on the outcome; no calculation yet. Just manual input.

**Comment by erksch** [comment]
@Askir Is the schedule an entity that has its own controller? Or is the schedule just the relation between matches and an event? 
I am looking for the right place to implement the action/view: 
A schedule being just a collection of matches, I would suggest rendering the schedule via an action in the MatchesController. Any thoughts?

**Comment by erksch** [comment]
Okay I figured out, a controller action like
```
# GET /event/1/schedule
def schedule
  @event = Event.find(params[:id])
  @matches = @event.matches
end
```
feels pretty unintuitive in the MatchesController.
I will move this to an EventsController. 

Furthermore, I need a working event model to be able to continue (#49 #61 @laurenzse) :wink:

**Comment by erksch** [comment]
Points have to be configurable for both teams!

**Comment by erksch** [comment]
Link to schedule page in show event page!

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.
