### ISSUE TITLE
Move Benachrichtigungseinstellungen to profile settings

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#511]
Currently `Benachrichtigungseinstellungen` are placed separately on the user menu. 
Notification settings should be integrated to the `Profil bearbeiten` page.

**Acceptance criteria**
- Notification settings function as earlier
- Settings are moved to the profile settings page under separate section after `Lieblingssportarten`

**Comment by birneamstiel** [comment]
also: remove notification settings page

**Comment by birneamstiel** [comment]
new position: append to existing form fields, after password fields
