### ISSUE TITLE
fix: forgot password

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#55]
**As a** user who lost the account password
**I want to** have a working recovery mechanism
**In order to** regain access to my account

**Tasks**:
- [x] find out how to send mails
- [x] templates
- [x] implement recover option

**Comment by ErikBrendel** [comment]
https://swt2-errbit-2017.herokuapp.com/apps/5a030ed1d901a0000620325e/problems/5a0ee64ef6e9230006bc91d0

**Comment by fpottbaecker** [comment]
Merged in PR #117

**Comment by fpottbaecker** [comment]
Estimated size: 8 (Unit: 30min)
Actual size: 10 (5h)
