### ISSUE TITLE
New Player Invite Form Design

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#555]
Width of "New Player Invitation Form" should be changed.

NOW:

![Screen Shot 2018-02-06 at 16.14.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f56b7191a379e90c2a55415d48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95fff48e14f55a0103560f43b.png)

HOW IT SHOULD BE:

![Screen Shot 2018-02-06 at 16.15.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f56b7191a379e90c2a54415a4abe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95fff48e14f57a6103561f43b.png)

**Comment by svitlanakalancha** [comment]
#490 already fix
