### ISSUE TITLE
Mail verification: unique email addresses

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#56]
**As an** admin
**I want to** have only one user per e-mail address
**In order to** identify my users via e-mail addresses (for example during login processes)

**Acceptance Criteria**:
- [x] sign up with existing e-mail addresses is not possible
- [x] e-mail addresses are used all lowercase (M@a.de == m@a.de)

**Out of Scope**:
- student.hpi.uni-potsdam.de and student.hpi.de are not the same (maybe new userstory)

**Comment by Markus-Brand** [comment]
Was already implemented

**Comment by fpottbaecker** [comment]
Estimated size: 3 (Unit: 30 min)
Actual size: 2.42 (1.21h)
