### ISSUE TITLE
Open ID Integration: registration via OpenID

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#58]
**As an** unregistered user with OpenIDAccount 
**I want to** sign up via OpenID
**In order to** simplify my login process

**Acceptance Criteria**:
- [x] after finishing the OpenID sign in you come to a page with an already partly filled form (depending on what openID transmits to our platform )

**Tasks**:
- [x] research
- [x] model adjustments
- [x] add signup via OpenID

**Comment by fpottbaecker** [comment]
Merged in #109

**Comment by fpottbaecker** [comment]
Estimated size: 13 (Unit: 30min)
Actual Size: 15.56 (7.78 h)
