### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#62]
AS a user
I WANT to be able to find footer on the bottom of every page
IN ORDER to quick access to some important links
![Screen Shot 2017-11-15 at 15.44.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f66b7191a379ea0c2f55415f47be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec958f14ee64d52a5153665f43b.png)

- every page of project has to have footer;
- footer has to have another color (not white);
- Design of footer is now not important;
- Link HPI --> hpi.de (should open in new tab); Link Impressum --> page "Impressum" (should open in same page)

**Comment by jkbe** [comment]
#### Estimation: S (Actual Size: M)

#### Tasks
- [x] Add imprint page (can be empty)
- [x] Add footer to application.html.erb (no duplicate code)
