### ISSUE TITLE
View list of participants

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#89]
**AS AN** organiser of an event
**I WANT TO** see a list of all participants in my event
**SO THAT** I know who is participating at my event

## ACCEPTANCE CRITERIA
- [x] When viewing the detailed event page of an event I created there should be a list of all teams/players who have joined the event

**Comment by fswt** [comment]
#29 -dependent
change single player to team

**Comment by GittiHab** [comment]
Table should show players beneath each other not next to each other (rows not columns)
