### ISSUE TITLE
remove double notification "Event was successfully created"

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#93]
There should be **only one notification "Event was successfully created"**.
The one with the green background should stay, and the lower one should be removed.

![image](https://user-images.githubusercontent.com/29160369/33021900-a9ad1bfa-ce03-11e7-879b-a67ddc4de939.png)

**same issue with event updates**

![image](https://user-images.githubusercontent.com/29160369/33024919-bab85960-ce0c-11e7-895f-deb266b7c9d3.png)

**only events seem to have this issue but please check again and ensure that only the message with the green background is shown**

![image](https://user-images.githubusercontent.com/29160369/33024991-eebe6d80-ce0c-11e7-979d-5ffb311f0467.png)

**Comment by erksch** [comment]
The occurences on teams show and event show seemed to be fixed already, I removed the double notification on the event index page in my commit.

**Comment by erksch** [comment]
Estimated: XSS
Actual: XSS
