### ISSUE TITLE
when signing up with an invalid password the password field offsets

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#94]
As can be seen in the picture below, an invalid password on sign up results in an offset of the password field. This should not happen. 

- [x]  the field should remain aligned. The text "is too short" should 

- [x]   The highlighting of the frame of the password field should be just like the blue highlighting of the Name (in the picture below) field, so following the line of the original text field (with 
rounded edges)
- [x] The highlighting of the frame should be the same red color as the red notification above). 

- [x]  The red background for "password" should be removed

- [x] The text "is too short" should start aligned with the left edge of the password field and when apparent should cause the text field beneath it to move down and maintain the gap to the content above

**Who it looks now:**
![image](https://user-images.githubusercontent.com/29160369/33022118-5884454a-ce04-11e7-80dc-9e5619cb217b.png)

**Who it should look like(approximately):**
![image](https://user-images.githubusercontent.com/29160369/33023435-6fe20994-ce08-11e7-8f88-42887f057ddd.png)

**Comment by fpottbaecker** [comment]
Part of the issue identified: [Removing this class from `scaffold.css`](https://github.com/hpi-swt2/sport-portal/blob/dev/app/assets/stylesheets/scaffold.css#L49) solves the offset issue.
