### ISSUE TITLE
Permissions of events

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#96]
**AS A** creator of an event (organiser)
**I WANT TO** be the only one to be able to edit my own events
**SO THAT** no one can manipulate my events

## ACCEPTANCE CRITERIA
- [x] Users who created an event can edit all events they created
- [x] Users can't edit events they did not create

**Comment by GittiHab** [comment]
This has not been reviewed by any PO

**Comment by MariusDanner** [comment]
This issue collides with issue #46 , where it is implemented with cancancan.
The current implementation doesn't comply with the standards that we agreed on. 
@GittiHab @zhamanakov

**Comment by GittiHab** [comment]
@MariusDanner, it is not our responsibility to ensure the correct implementation. In fact, it is only our task to make sure the correct functionality is implemented.

This User Story does not collide out of my perspective nor has it been taken into the sprint by my team. My team solved this story as a side effect of their last sprint and it fulfilled my expectations.

**Comment by emanuel-metzenthin** [comment]
It does collide with our issue. But you're right, it is more the responsibility of @jacobfreise and @pawelsoundso.
