### ISSUE TITLE
Multiple organisers

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#97]
**AS A** creator of an event (organiser)
**I WANT TO** be able to add other organisers of an event
**SO THAT** I don't have to organise all events alone

## ACCEPTANCE CRITERIA
- [ ] Organisers of an event (users with edit permission to an event) can add other users as organisers to the event
- [ ] All organisers of an event have edit permission for the event

**Comment by svitlanakalancha** [comment]
See #217
